### ISSUE TITLE
Peer review -- seeking a home

### ISSUE THREAD

**Issue by notjames** [samsung-cnct/skopos#4]
So I wrote this as a tool over the weekend. I use to switch between kraken envs. I showed it to a few people who believe there's potential use for it at least in the meantime. So I polished a bit today and am presenting it to commontools.

Requesting a general peer review and a home if everyone signs off.

**Comment by mikeln** [comment]
A couple of items:
1) it assumes the user's config is always off of $HOME.  This may not be true.   You should allow the user to specify where the base for their kraken config lives,  if it is not specified then default to $HOME.

2) Are you checking for the needed prerequisite software installation? i.e ruby jq etc?  Advise the user what it needed if it is missing.

**Comment by coffeepac** [comment]
this is a neat idea but it isn't something that common tools has bandwidth to absorb right now.  I can see something like this being very useful, especially when we are managing a pipeline of clusters so I would encourage you to keep hacking on it as its useful to you.

my first comment on that end is that there is no GKE support.  I'll file an issue for that now.  Otherwise I don't have a lot of input.

**Comment by notjames** [comment]
I appreciate your feedback guys. I'll continue to hack at it and submit issues as I find them. @mikeln I'll create issues from your comments#1,2, & 3 as I believe they are valid. As to your comment #4, yes. Prereqs are already being checked and an exit+error occur when prereqs are not satisfied. comment#5 is one I'll have to think about. I might be able to come up with something for this.
